# Generated by Django 5.0.7 on 2024-07-16 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('forma_pago', models.CharField(choices=[('EF', 'Efectivo'), ('DE', 'Débito'), ('CR', 'Crédito'), ('TR', 'Transferencia')], default='EF', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioVideojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='videojuego',
        ),
        migrations.RemoveField(
            model_name='itemorden',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='itemorden',
            name='videojuego',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.RenameField(
            model_name='videojuego',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='imagen',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='foto',
            field=models.ImageField(default='default_game.png', upload_to='videojuegos/'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.videojuego')),
            ],
            options={
                'unique_together': {('usuario', 'videojuego')},
            },
        ),
        migrations.CreateModel(
            name='DetallesPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videojuego_nombre', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='myapp.pedido')),
            ],
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
        migrations.DeleteModel(
            name='ItemOrden',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
