# Generated by Django 5.0.7 on 2024-07-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pedido_usuariovideojuego_remove_itemcarrito_carrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='foto',
            field=models.ImageField(default='img/default_game.png', upload_to='img/'),
        ),
    ]
